modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/ExCompressum/issues"

[[mods]]
modId="excompressum"
version="${mod_version}"
displayName="ExCompressum"
displayURL="https://mods.twelveiterations.com/mc/excompressum"
logoFile="excompressum-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Ex Nihilo Addon. Attempts to reduce grind by adding pre-automation tools like compressed hammers.
'''

[[dependencies.excompressum]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.excompressum]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.excompressum]]
modId="balm"
mandatory=true
versionRange="${balm_version_range}"
ordering="NONE"
side="BOTH"
